### ISSUE TITLE
ignored_packages not woking in Preferences.sublime-settings in project folder

### ISSUE THREAD

**Issue by easyfrog** [TobyGiacometti/SublimeSuperSettings#1]
I create a `Preferences.sublime-settings` in project's folder, and want to ignored some packages ONLY in this project. but not working.

<img width="375" alt="image" src="https://user-images.githubusercontent.com/10724325/200115319-0b6256f7-7a4a-4c20-8482-823b15768fbc.png">

**Comment by TobyGiacometti** [comment]
The `ignored_packages` setting cannot be controlled by this package as it is an application-global setting that affects all windows/tabs.
